version: '3.8'

services:
  addition-service:
    image: addition-service
    build:
      context: .
      dockerfile: AdditionService/Dockerfile
    ports:
      - "5000:80"

  subtraction-service:
    image: subtraction-service
    build:
      context: .
      dockerfile: SubtractionService/Dockerfile
    ports:
      - "5001:80"

  history-service:
    image: history-service
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    ports:
      - "5002:80"
  calculator-api:
    image: calculator-api
    build:
      context: .
      dockerfile: CalculatorAPI/Dockerfile
    ports:
      - "5003:80"

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
