version: '3.8'

services:
  addition-service:
    image: addition-service
    build:
      context: .
      dockerfile: AdditionService/Dockerfile
    ports:
      - "80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - calcnet
  subtraction-service:
    image: subtraction-service
    build:
      context: .
      dockerfile: SubtractionService/Dockerfile
    ports:
      - "80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - calcnet
  history-service:
    image: history-service
    build:
      context: .
      dockerfile: HistoryService/Dockerfile
    ports:
      - "80"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    networks:
      - calcnet
  calculator-api:
    image: calculator-api
    build:
      context: .
      dockerfile: CalculatorAPI/Dockerfile
    ports:
      - "5003:80"
    deploy:
      replicas: 1 
      restart_policy:
        condition: on-failure
    networks:
      - calcnet
    

  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
    ports:
      - "5341:80"
    deploy:
      replicas: 1

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    deploy:
      replicas: 1
networks:
  calcnet:
    driver: bridge